name: climbjio
description: A shared calender for friends to climb together.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0-nullsafety.2
  firebase_auth: ^3.3.11
  firebase_core: ^1.13.1
  badges: ^2.0.2
  cupertino_icons: ^1.0.3
  animated_widgets: ^1.1.0
  animated_text_kit: ^4.2.1
  animations: ^2.0.2
  http: ^0.13.4
  font_awesome_flutter: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  # TODO: Insert Fonts (103)
  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Regular.ttf
        - asset: fonts/Rubik-Medium.ttf
          weight: 500
  uses-material-design: true
  assets:
    - assets/diamond.png
    