version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    working_directory: '/home/circleci/project/tests/'
    jobs:
      - cypress/run:
          record: true
          
#           command: "echo Hello, World!; pwd; whoami; ls; ls /home/circleci/project/tests"
