version: 2
jobs:
  cypress/run:
    docker:
    - image: cypress/base:12.14.0
    parallelism: 1
    steps:
    - checkout
    - restore_cache:
        keys:
        - cache-{{ .Branch }}-{{ checksum "package.json" }}
    - run:
        name: check
        command: apt-get update && apt-get install -y python3-pip && pip3 install flask && pip3 install django
    - run:
        name: start flask
        command: nohup python3 cjtest.py & ; sleep 10; curl 127.0.0.1:5011/cjtest/;
    - run:
        name: Npm CI
        command: cd ./tests && npm ci
    - run:
        command: cd ./tests && npx cypress verify
    - save_cache:
        key: cache-{{ .Branch }}-{{ checksum "package.json" }}
        paths:
        - ~/tests/.npm
        - ~/tests/.cache
    - persist_to_workspace:
        root: ~/
        paths:
        - project
        - .cache/Cypress
    - attach_workspace:
        at: ~/
    - run:
        name: Run Cypress tests
        command: 'cd ./tests && npx cypress run --record'
workflows:
  build:
    jobs:
    - cypress/run
  version: 2
