version: 2.1
orbs:
  cypress: cypress-io/cypress@1
jobs:
  build:
    working_directory: '/home/circleci/project/tests/'
    cypress/run:
      record: true
      
workflows:
  build:
    jobs:
      - build
          
